version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fan-out-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ikyeet87s7dm"
s3_prefix = "fan-out-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "MyWebhookURL=\"https://webhook.site/bab1d946-3b3f-4577-b4d3-7a66d32c88f6\""
image_repositories = []
